# Generated by Django 3.1.5 on 2021-01-22 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_usage', models.IntegerField()),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='authtoken.token')),
            ],
        ),
        migrations.CreateModel(
            name='TokeUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('token_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tokeninfo.tokeninfo')),
            ],
        ),
    ]
