# Generated by Django 3.1.5 on 2021-01-22 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokeninfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TokeUsage',
            new_name='TokenUsage',
        ),
    ]
